name: Simpletwist
favicon: null
layout_spectrum: 0.30239
typography_spectrum: 0.60202
title: The Itty Bitty Production Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#302a2e'
    - '#e76323'
    - '#987b4f'
    - '#cbab7c'
  brandStrength: 0.8057019300758839
  lightness: 0.8366017714142799
  saturation: 0
  rhythmicContrast: 0.2098927905317396
purpose: []
