name: Simpletwist
favicon: null
layout_spectrum: 0.25271
typography_spectrum: 0.19889
title: 'Simpletiwst: The Itty Bitty Production Company'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f9f9f7'
    - '#4c4846'
    - '#948879'
    - '#de4f56'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
