typography_spectrum: 0.8615270417649299
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.3527988255955279
  lightness: 0.1932853397447616
  saturation: 0.9910181979648769
  rhythmicContrast: 0.00986730633303523
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10981331951916218
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jeremy
  email: jeremy.s.romero@gmail.com
  url: simpletwist.com
name: Simpletwist
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Simpletiwst: The Itty Bitty Production Company'
purpose: []
